apiVersion: v1
kind: ConfigMap
metadata:
  name: openssl-server-certs
data:
  ca_cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICuDCCAaCgAwIBAgIBATANBgkqhkiG9w0BAQ0FADANMQswCQYDVQQDEwJjYTAe
    Fw0xOTA5MTcwMzAwMDhaFw0yMDA5MTYwMzAwMDhaMA0xCzAJBgNVBAMTAmNhMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuuUlPeM0OajCuuAf+l78i4Vq
    GYNjVfr0T6YZZ2GhgaLptPdxOa0SdUAli72+n27nMuiCk07kSJv+iGIYJEn7SGmm
    j3EWP+dLg+yaCG85BXjCfGsJfBm210o74wqMXB6ipiSPmgYb+5tY+voqXHzDXu7U
    WZF1rMBnp7p9Zn6f6i8Fz1gIefQo4gEj3STM0rUfIPlQkCb+Y8g3Q+QB+A/WC+hX
    iiL3BpLd/+yuzuo68RMRsCQs3bDnAqs+nXL3seHdl0z57uBGIjqP+3cSW3ILqFMh
    XFuu+8S2Rjg6+G5QmuE6YbsTC/1NBz4CDk3GgdI8nXuVIkPPAveS4TBaA7T09QID
    AQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG
    9w0BAQ0FAAOCAQEAgR8uAd5p+hOcysp1Y96wLZA7hS/h/ETF0i09Ybm6kY50DPeZ
    nJCCoBpj+OnkNOht/SYip77YnNCRhEueo/gFl4R4iTQr0nnlJp7ciDUL2arm9u0a
    +1ElOGm54NjzXw9JDYNvVAmFZwEEfv6AEPlRqScqut2PgNxGd0qxohG8f3scLbht
    ueAEcfVr8VIy9rPBMuw/2HBLLAQ2n/zxdxyU+xczLAy6i1cASE0uFuM483DC6hlV
    R3q5QgYpp6HsbZ8brx85+EXxBjuIBbGYox30d02NO0Dqw/0y98vKs4TXx1b5YZLi
    xD56oyFC//mDXvrx7HkmRzsoVKhsU/PuiMiCOw==
    -----END CERTIFICATE-----
  server_cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwDCCAaigAwIBAgIBAjANBgkqhkiG9w0BAQ0FADANMQswCQYDVQQDEwJjYTAe
    Fw0xOTA5MTcwMzAwMDhaFw0yMDA5MTYwMzAwMDhaMBExDzANBgNVBAMTBnNlcnZl
    cjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMLD5eqQfwH9cGsP2VmL
    wIsUfTfWv9wudcrGXqG549i4+uCFfcolbarKX5gluiV3cbHZ1Wi1b2h8MERVcDSM
    wktoSzPASdMcDdWGfBCwAEMIuP4rYUW3XLfLVQOpdD2JzEnMW2U2Jxfn1DGQa5DL
    B40Q6ZS0eWiFZXbUE44hDl5pkBkQK9lmQFeEQC836yeJlK/1GUDtldO7mTrRrSjf
    Luj9rSzkrQBhCCwfwLphHCR2RHN7OgH3ll9Edh6iJ0IfH7fu2aRNsbfpJw2N8rzW
    qdBq3R+B2KnJtgAPf7Rl601Vu1Mnp6D/ICdsUVf9UuwfJ1X1u7G8wwIVePrWgteZ
    YMMCAwEAAaMnMCUwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMB
    MA0GCSqGSIb3DQEBDQUAA4IBAQBndjXAOradaHMKwlVbXqVpnDm9rfpMVW4rhEEH
    YpSprz03a2gB3lSxNSfm7kUvEXTmEheSL83fubRoWNbLb28KYzm7mrFz5BGjBfH+
    K5I18s3oSW6zpK6O/Fu+gimc1eT7VgE9M0/mo1sj/4f9KPfnbfY6YbZh9wggkkit
    lathSqmPMG/PeENo69Xh0ubEuDit21w0FXeo2TqLpstXe7Zu6Lw56AJiVTmmNWCl
    8hrNk4tttsI0gbFwNlXKqBsScMaVC325DYm76fjF1guvkkdm4vvaQ+aF8JN1RM4a
    5+7rViVRSgT+LU9TfekWkZcr2zDsk991FSjauvQRIQQDYthm
    -----END CERTIFICATE-----
  server_key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCw+XqkH8B/XBr
    D9lZi8CLFH031r/cLnXKxl6huePYuPrghX3KJW2qyl+YJbold3Gx2dVotW9ofDBE
    VXA0jMJLaEszwEnTHA3VhnwQsABDCLj+K2FFt1y3y1UDqXQ9icxJzFtlNicX59Qx
    kGuQyweNEOmUtHlohWV21BOOIQ5eaZAZECvZZkBXhEAvN+sniZSv9RlA7ZXTu5k6
    0a0o3y7o/a0s5K0AYQgsH8C6YRwkdkRzezoB95ZfRHYeoidCHx+37tmkTbG36ScN
    jfK81qnQat0fgdipybYAD3+0ZetNVbtTJ6eg/yAnbFFX/VLsHydV9buxvMMCFXj6
    1oLXmWDDAgMBAAECggEAXjvkWUqSeQcDxnlDo2TPwzslnsfDyqecDIFQNhW33Rsb
    H1jXVOApIJKMEBRo7UnOc8u+ysvGXJqBy/4+rN5R/6Q1hpOJ5J/VPbO1AWn2pnho
    8WlRxiaCsNarinsJp+CtPCOpMN4zqghcDaMfuE3TmHhPW8i6WUz5m7XexEzQI/M9
    NP8G1nQsWPP3o+OHC79SmMK38qKzrB8A0zpbVlVLuTW/MT4H17g+H+QaV60ErBD9
    EYrXptwI4IrG6ID/yBs+Jg32ktUrjQKXLQIf4C1/9ToHbPM6y8p88VEpOOwZxa7C
    5ZWOMJXsAONWYY1pS6olhjXLJ7C6gLc6INtDjrlsSQKBgQDXp1cydqiKiXAl/upb
    466Z2Vt2wrXY9F5RYrOtZr1Kqw2Gu4KjMdkaF3uSk/jKQsUYV2TelloayJwCcLAt
    FmMWKyFD5I6mk0bKDFUYToBFces/0Js4RHML0bpCNGVExM2MB2o9F+/Xl/8FICpU
    kcNLHUUa1BVUpzFU4o/yv2yGLwKBgQDnNBzHcp8SuqCK7VMVFnrUqp8mt3P4l8/y
    pMCsgfvlybeqUG78xSxWnTm/HCrg2mNsmIxAbN575hIpXIR5pCQqiy3tlNR90xVg
    Lk03IKbqTR/mGzvaAfHD7b6qqPbmef7Z6qtn+6k02sX9eIjIsDdPc1EJQmEBTcYo
    VzyvjG69rQKBgD33yAaoMiYc+Czy40UkV7e9zZqCuN5u2etpAViCfUJHhMuCdjeO
    y2PD+65S9tqn9RrZghK0AZBQtQO+feF23WIxYo2vz43uJBlLEei6JgHOilr8Bp5U
    jPqIeY0soSzxoF7sgoqrpi+9bXp7k65ZdFTRRFpBNx/sKzDJKbQHbZfhAoGBAJjI
    iywRxqTtxyGHaxvIWysmBT3khTKFv9ksnlZhH0DeaAyYUn+fHImwJHTx/DPSnVkq
    BaSdTPi7NM04YiKwIWYryxHxA+qSDtIcRtJjNWonxSieXpLWLhm3hgPo3B+6Bnui
    49o3J73RxHyXpmxYZnSOU8K2prvh1UzbOTMYriWRAoGBAJY/FuJ24BgauFYrMW1t
    qK7uUNVwNxaAMV+1AIfHL/TXO9DqXsizKJTgEqgaxLaGiS3C98S7s8Tu2MSnVJJ7
    XT28KqHxrTU7n3prWkWKcFKj5lldEVBgiSWDV4faHvAXMOrgqpMFD3IrzGvSZX+S
    FM5ljQGr/sVhP5UXqZ7xFGXB
    -----END PRIVATE KEY-----
